apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nifi-zookeeper01-deployment
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nifi-zookeeper
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper01
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper01
        name: zookeeper01
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181