---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-broker1
  namespace: demo
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: '80'
#        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,BROKER:PLAINTEXT
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka.services.devlabs.com
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
#        - name: KAFKA_CREATE_TOPICS
#          value: topic1:3:3